### ISSUE TITLE
Exemplo de testes de API dinâmicos 

### ISSUE THREAD

**Issue by GiovaniRSantos** [driuzzo/cypress-faq#13]
- Utilização de app actions para centralizar métodos que serão reutilizados na feature
- Exemplos de testes cobrindo um CRUD
- Métodos genéricos para abranger responsabilidades e reutilização em todas as features
- Documentação dos métodos utilizando a interface Chainable
- Utilização de typescript para um melhor desenvolvimento

PR: https://github.com/driuzzo/cypress-faq/pull/12

**Comment by driuzzo** [comment]
@all-contributors please add @GiovaniRSantos for code

**Comment by driuzzo** [comment]
@GiovaniRSantos obrigado pela contribuição e seja bem vindo ao time de contribuidores!
